### ISSUE TITLE
Documentation confusion

### ISSUE THREAD

**Issue by nabeelio** [konsulting/laravel-transformer#3]
Hi, this library looks pretty cool. I'm a little lost on the docs - the section on `TransformingRequest`, however there's a bit that's crossed out under it, and it doesn't seem like that trait exists in the code. Is this not there anymore?

**Comment by rdarcy1** [comment]
Thanks for flagging, looks like that was just a mistake in the readme. There is a [`TransformingRequest`](https://github.com/konsulting/laravel-transformer/blob/master/src/TransformingRequest.php) trait available that can be attached to the Request object. 

Let me know if you need any help with it.

**Comment by nabeelio** [comment]
Thanks. Well the FormRequest would act differently than the Request
transformer, do was just wondering about that, since it doesn't seem to be
there. No worries, though. I have something in FormRequest already, so I
might just hook something in.

>

**Comment by rdarcy1** [comment]
Sorry not entirely sure what you mean there – the `TransformingRequest` trait is designed to be attached to a `FormRequest` class. This enables you to create a `transformRules()` method in the same way that you'd create a `rules()` method for your validation rules, so you only have to declare rules rather than explicitly call the transformer.

On the base Laravel `Request` class, there's a [macro registered](https://github.com/konsulting/laravel-transformer/blob/d2b3cf809136ce73ca232445be5b092935cce31f/src/TransformerServiceProvider.php#L57) to perform transformation, which the above trait makes use of (but to use `TransformingRequest` all you have to do is create the `transformRules()` method, no need to call the macro explicitly).

**Comment by nabeelio** [comment]
Yeah, I just saw you fixed the documentation up. Thanks!
